; MIDI Foot Pedal - ESP32-S3 Super Mini
; PlatformIO Configuration

[env:esp32s3_super_mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board = esp32s3_super_mini
framework = arduino
build_flags =
    -DBOARD_HAS_NEOPIXEL
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
monitor_speed = 115200
